In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator

## 📂 Import Dataset

### ⚙️ [1] Train Set

In [2]:
dataset = pd.read_csv("/home/kannika/code/mini-ImageNet_MachineUnlearn.csv", dtype=str)
print(dataset.shape)
dataset.head()

(60000, 6)

,Unnamed: 0,img_path,filename,label,cls,subset
0,0,/media/HDD/mini-ImageNet/mini-imagenet/train/n...,n0444325700001135.jpg,n04443257,TRUE,train
1,1,/media/HDD/mini-ImageNet/mini-imagenet/train/n...,n0444325700000414.jpg,n04443257,TRUE,train
2,2,/media/HDD/mini-ImageNet/mini-imagenet/train/n...,n0444325700000025.jpg,n04443257,TRUE,train
3,3,/media/HDD/mini-ImageNet/mini-imagenet/train/n...,n0444325700000324.jpg,n04443257,TRUE,train
4,4,/media/HDD/mini-ImageNet/mini-imagenet/train/n...,n0444325700000491.jpg,n04443257,TRUE,train

In [3]:
print(set(dataset["subset"]))
print(set(dataset["cls"]))

{'test', 'val', 'train'}
{'FALSE', 'TRUE'}

In [4]:
dataset["img_path"][0]

'/media/HDD/mini-ImageNet/mini-imagenet/train/n04443257/n0444325700001135.jpg'

In [5]:
'''
new path = /media/tohn/HDD2/miniImageNet_Dataset
'''

newpath = "/media/tohn/HDD2/miniImageNet_Dataset/"
oldpath = "/media/HDD/mini-ImageNet/"

dataset['img_path'] = dataset['img_path'].str.replace(oldpath, newpath)
print(dataset.shape)
dataset.head()

(60000, 6)

,Unnamed: 0,img_path,filename,label,cls,subset
0,0,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,n0444325700001135.jpg,n04443257,TRUE,train
1,1,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,n0444325700000414.jpg,n04443257,TRUE,train
2,2,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,n0444325700000025.jpg,n04443257,TRUE,train
3,3,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,n0444325700000324.jpg,n04443257,TRUE,train
4,4,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,n0444325700000491.jpg,n04443257,TRUE,train

In [6]:
dataset["img_path"].tolist()

['/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001135.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000414.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000025.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000324.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000491.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000404.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000813.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000382.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000361.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001210.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001011.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000133.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000851.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000452.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001031.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000377.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001100.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000241.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000711.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000567.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001085.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000820.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000944.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001020.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000688.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001144.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000940.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000149.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000142.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001018.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000355.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000405.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000982.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000535.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000987.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000055.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001243.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000809.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000130.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000956.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000768.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000235.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000799.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001181.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000544.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000240.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000602.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000519.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001128.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000116.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000639.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000608.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000849.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001104.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000894.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001221.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000977.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000921.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001070.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000411.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000795.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000007.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001111.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000975.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000735.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000456.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000957.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000136.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000670.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000409.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000630.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001029.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000777.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000964.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000285.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000994.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000867.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000272.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000501.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000358.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001244.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000646.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000620.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000810.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000434.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000966.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000680.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000155.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001236.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001204.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000277.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000907.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000227.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000953.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000214.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000426.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000671.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000230.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000536.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001211.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000449.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000564.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000028.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000593.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000211.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000006.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001101.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000164.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000326.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001002.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000523.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000096.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000016.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000185.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001023.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000866.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000920.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000774.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000619.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001086.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000931.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000642.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000540.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000337.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000743.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000029.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000721.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000610.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000841.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000669.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000580.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001139.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000951.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000504.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000844.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000040.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001150.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000699.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000350.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000843.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000212.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000243.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000464.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000698.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000596.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000897.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000283.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000425.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000649.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001138.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000996.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000145.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000893.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001222.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000484.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000770.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001249.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000193.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000562.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000298.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000206.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000818.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001146.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000351.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000175.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001239.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000165.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000062.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001230.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001143.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000764.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000634.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000094.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000582.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000330.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000266.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000493.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000030.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000693.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000679.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000594.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000928.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001133.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000297.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000362.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000908.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001241.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000604.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000974.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000339.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000712.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000321.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001120.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000963.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000438.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000865.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000134.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000691.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001043.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000573.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001028.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001121.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000695.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000911.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000665.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000322.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001047.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000577.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001156.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000057.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700001190.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/train/n04443257/n0444325700000388.jpg',

In [8]:
dataset["img_path"].tolist()[55500:]

['/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000592.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000461.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000137.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000681.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000285.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000209.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000508.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000442.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000105.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000023.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001148.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001208.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000896.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000021.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000343.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000961.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001164.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000716.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001218.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001195.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000085.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000713.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000790.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000582.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000882.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001182.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000488.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000484.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000223.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000501.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001206.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000867.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001196.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000954.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000646.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001074.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000363.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001078.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000596.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000893.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000578.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000334.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000715.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000669.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000273.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000574.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001215.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000914.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001032.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000472.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000077.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000465.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000421.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000217.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000952.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000428.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000664.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000115.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000361.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000791.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001272.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000113.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000840.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000786.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000485.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000718.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000353.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000198.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000496.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000891.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000411.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001101.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000610.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000155.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000605.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001116.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000157.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000811.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001126.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000358.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000587.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000910.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000602.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000325.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001082.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000943.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000236.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000564.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001185.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000556.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001294.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000121.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001298.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000524.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000180.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001132.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001158.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000927.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000244.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000803.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000579.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001201.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000082.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000087.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000377.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000324.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001030.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001159.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000272.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000090.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000836.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000536.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000299.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000763.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000026.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000067.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000938.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000436.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000567.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000163.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000546.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000416.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001275.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000255.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000346.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000448.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001058.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000269.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000466.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000268.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000684.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000947.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001266.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000347.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000257.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001124.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000486.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000386.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000152.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000168.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000479.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000553.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000177.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000668.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000810.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000696.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001061.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000447.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000191.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000883.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000412.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000034.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000367.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001268.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000594.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000227.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000313.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001160.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000138.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000600.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000722.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001013.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000897.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000122.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000554.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000024.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001010.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000537.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000494.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000686.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000490.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000512.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001137.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000626.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000143.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000907.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000274.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000463.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000552.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000709.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001102.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001299.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000256.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000396.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000757.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000277.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000711.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000234.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001152.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001234.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000247.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001012.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000705.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000030.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000598.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000145.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000387.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000858.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001190.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000065.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000526.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001018.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001041.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000736.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000517.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000585.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000771.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000376.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000688.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000595.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000429.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000405.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000842.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800000838.jpg',
 '/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet/test/n04522168/n0452216800001188.jpg',

In [9]:
from PIL import Image, ImageFile
from efficientnet.keras import center_crop_and_resize, preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [10]:
height=width = 224
BATCH_SIZE = 16

train_datagen = ImageDataGenerator(
      rescale=1./255,
      rotation_range=30,
      width_shift_range=0.2,
      height_shift_range=0.2,
      brightness_range=[0.5, 1.5],
      shear_range=0.4,
      zoom_range=0.2,
      horizontal_flip=False,
      fill_mode='nearest')

train_generator = train_datagen.flow_from_dataframe(
    dataframe = dataset,
    directory = None,
    x_col = 'img_path',
    y_col = 'cls',
    target_size = (height, width),
    batch_size=BATCH_SIZE,
    color_mode= 'rgb',
    class_mode='categorical')

Found 60000 validated image filenames belonging to 2 classes.

In [11]:
dataset.to_csv("/home/kannika/code/mini-ImageNet_MachineUnlearn.csv")

---------------

### ⚙️ [2] Test Set

In [13]:
datatest = pd.read_csv("/home/kannika/code/DATATEST-V2_mini_ImageNet_MachineUnlearn.csv", dtype=str)
print(datatest.shape)
datatest.head()

(6000, 7)

,Unnamed: 0,filename,img_path_main,img_path_2,cls,encode_label,subset
0,0,n0444325700001113,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,TRUE,1,test
1,1,n0444325700000041,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,TRUE,1,test
2,2,n0444325700000976,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,TRUE,1,test
3,3,n0444325700000294,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,TRUE,1,test
4,4,n0444325700000506,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,/media/HDD/mini-ImageNet/mini-imagenet-DATATES...,TRUE,1,test

In [14]:
print(datatest["img_path_main"][0])
print("-"*125)
print(datatest["img_path_2"][0])

/media/HDD/mini-ImageNet/mini-imagenet-DATATESTV2/n0444325700001113_batchmain.jpg
-----------------------------------------------------------------------------------------------------------------------------
/media/HDD/mini-ImageNet/mini-imagenet-DATATESTV2/n0444325700001113_batch2.jpg

In [15]:
print(set(datatest["subset"]))
print(set(datatest["cls"]))

{'test'}
{'FALSE', 'TRUE'}

In [16]:
'''
new path = /media/tohn/HDD2/miniImageNet_Dataset
'''

newpath = "/media/tohn/HDD2/miniImageNet_Dataset/"
oldpath = "/media/HDD/mini-ImageNet/"

datatest['img_path_main'] = datatest['img_path_main'].str.replace(oldpath, newpath)
datatest['img_path_2'] = datatest['img_path_2'].str.replace(oldpath, newpath)
print(datatest.shape)
datatest.head()

(6000, 7)

,Unnamed: 0,filename,img_path_main,img_path_2,cls,encode_label,subset
0,0,n0444325700001113,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,TRUE,1,test
1,1,n0444325700000041,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,TRUE,1,test
2,2,n0444325700000976,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,TRUE,1,test
3,3,n0444325700000294,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,TRUE,1,test
4,4,n0444325700000506,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,/media/tohn/HDD2/miniImageNet_Dataset/mini-ima...,TRUE,1,test

In [17]:
print(datatest["img_path_main"][0])
print("-"*125)
print(datatest["img_path_2"][0])

/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet-DATATESTV2/n0444325700001113_batchmain.jpg
-----------------------------------------------------------------------------------------------------------------------------
/media/tohn/HDD2/miniImageNet_Dataset/mini-imagenet-DATATESTV2/n0444325700001113_batch2.jpg

In [20]:
print("-------------- [INFO]: Check Image Path Main --------------")
train_generator = train_datagen.flow_from_dataframe(
    dataframe = datatest,
    directory = None,
    x_col = 'img_path_main',
    y_col = 'cls',
    target_size = (height, width),
    batch_size=BATCH_SIZE,
    color_mode= 'rgb',
    class_mode='categorical')

-------------- [INFO]: Check Image Path Main --------------
Found 6000 validated image filenames belonging to 2 classes.

In [21]:
print("-------------- [INFO]: Check Image Path 2 --------------")
train_generator = train_datagen.flow_from_dataframe(
    dataframe = datatest,
    directory = None,
    x_col = 'img_path_2',
    y_col = 'cls',
    target_size = (height, width),
    batch_size=BATCH_SIZE,
    color_mode= 'rgb',
    class_mode='categorical')

-------------- [INFO]: Check Image Path 2 --------------
Found 6000 validated image filenames belonging to 2 classes.

In [22]:
datatest.to_csv("/home/kannika/code/DATATEST-V2_mini_ImageNet_MachineUnlearn.csv")

--------------