In [1]:
import numpy as np
import pandas as pd

## DATASET: Train Set

In [2]:
dataframe = pd.read_csv('/media/tohn/HDD/VISION_dataset/Traindf_fold4_8_v1.csv')
print(dataframe.shape)
dataframe.head()

(4601, 27)

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Rwidth,Rheight,Sub_class_New,tag_AjNit,tag_AjWan,Test150,Spilt,Sub_Position_New,filename,Sub_Position_Label
0,34,42,P5,P52,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,7,MildFattyLiver,...,0.633663,0.651394,AB01,NaN,NaN,False,Train,None,AB01 P5-2 C042.JPG,P7
1,35,42,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,7,ModerateFattyLiver,...,0.541516,0.422222,AB02,NaN,NaN,False,Train,P1,AB02 P1 C042.JPG,P1
2,36,42,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,7,ModerateFattyLiver,...,0.494585,0.610101,AB02,NaN,NaN,False,Train,P2,AB02 P2 C042.JPG,P2
3,37,42,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,7,ModerateFattyLiver,...,0.494545,0.668687,AB02,NaN,NaN,False,Train,P6,AB02 P5-1 C042.JPG,P6
4,38,42,P4,P42,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,7,ModerateFattyLiver,...,0.477148,0.690909,AB02,NaN,NaN,False,Train,P5,AB02 P4-2 C042.JPG,P5

In [4]:
print(set(dataframe.fold))

{4, 5, 6, 7, 8, 9, 10}

## DATASET: Validation Set

In [5]:
dataval = pd.read_csv('/media/tohn/HDD/VISION_dataset/Valdf_fold3_v1.csv')
print(set(dataval.fold))
print(dataval.shape)
dataval.head()

{3}
(656, 27)

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Rwidth,Rheight,Sub_class_New,tag_AjNit,tag_AjWan,Test150,Spilt,Sub_Position_New,filename,Sub_Position_Label
0,0,15,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,3,MildFattyLiver,...,0.712707,0.649402,AB01,NaN,NaN,False,Train,P3,AB01 P3-1 C015.JPG,P3
1,1,15,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,3,MildFattyLiver,...,0.595628,0.683267,AB01,NaN,NaN,False,Train,P1,AB01 P1 C015.JPG,P1
2,2,15,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,3,MildFattyLiver,...,0.497278,0.501992,AB01,NaN,NaN,False,Train,P2,AB01 P2 C015.JPG,P2
3,3,15,P4,P42,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,3,MildFattyLiver,...,0.718412,0.679283,AB01,NaN,NaN,False,Train,P5,AB01 P4-2 C015.JPG,P5
4,4,15,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,3,MildFattyLiver,...,0.608229,0.577689,AB01,NaN,NaN,False,Train,P4,AB01 P4-1 C015.JPG,P4

## Combine DATASET: Train Set + Validation Set (Fold3-Fold10)

In [7]:
# รวมข้อมูล (ต่อแถว)
df_merged = pd.concat([dataframe, dataval], ignore_index=True)
# ตรวจสอบขนาดของข้อมูลที่รวมแล้ว
print("Merged shape:", df_merged.shape)
print("Fold Number: ", set(df_merged.fold))
# แสดงข้อมูลตัวอย่าง
df_merged.head()

Merged shape: (5257, 27)
Fold Number:  {3, 4, 5, 6, 7, 8, 9, 10}

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Rwidth,Rheight,Sub_class_New,tag_AjNit,tag_AjWan,Test150,Spilt,Sub_Position_New,filename,Sub_Position_Label
0,34,42,P5,P52,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,7,MildFattyLiver,...,0.633663,0.651394,AB01,NaN,NaN,False,Train,None,AB01 P5-2 C042.JPG,P7
1,35,42,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,7,ModerateFattyLiver,...,0.541516,0.422222,AB02,NaN,NaN,False,Train,P1,AB02 P1 C042.JPG,P1
2,36,42,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,7,ModerateFattyLiver,...,0.494585,0.610101,AB02,NaN,NaN,False,Train,P2,AB02 P2 C042.JPG,P2
3,37,42,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,7,ModerateFattyLiver,...,0.494545,0.668687,AB02,NaN,NaN,False,Train,P6,AB02 P5-1 C042.JPG,P6
4,38,42,P4,P42,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,7,ModerateFattyLiver,...,0.477148,0.690909,AB02,NaN,NaN,False,Train,P5,AB02 P4-2 C042.JPG,P5

In [9]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5257 entries, 0 to 5256
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          5257 non-null   int64
 1   Case                5257 non-null   int64
 2   Abs Position        5257 non-null   object
 3   Sub Position        5257 non-null   object
 4   Class               5257 non-null   object
 5   Path Full           5257 non-null   object
 6   Path Crop           5257 non-null   object
 7   Views               5257 non-null   object
 8   fold                5257 non-null   int64
 9   15AB                5257 non-null   object
 10  originalImage       1823 non-null   object
 11  left                1823 non-null   float64
 12  top                 1823 non-null   float64
 13  width               1823 non-null   float64
 14  height              1823 non-null   float64
 15  Rleft               1823 non-null   float64
 16  Rtop                1823 non-null   float64
 17  Rwidth              1823 non-null   float64
 18  Rheight             1823 non-null   float64
 19  Sub_class_New       5257 non-null   object
 20  tag_AjNit           0 non-null      float64
 21  tag_AjWan           0 non-null      float64
 22  Test150             5257 non-null   bool
 23  Spilt               5257 non-null   object
 24  Sub_Position_New    5257 non-null   object
 25  filename            5257 non-null   object
 26  Sub_Position_Label  5257 non-null   object
dtypes: bool(1), float64(10), int64(3), object(13)
memory usage: 1.0+ MB

In [14]:
fold_df = df_merged[df_merged["fold"]==5].reset_index(drop=True)
print("Fold: ", set(fold_df.fold))
print(fold_df.shape)
fold_df.head()

Fold:  {5}
(659, 27)

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Rwidth,Rheight,Sub_class_New,tag_AjNit,tag_AjWan,Test150,Spilt,Sub_Position_New,filename,Sub_Position_Label
0,53,22,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,5,MildFattyLiver,...,0.602914,0.571713,AB01,NaN,NaN,False,Train,P2,AB01 P2 C022.JPG,P2
1,54,22,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,5,MildFattyLiver,...,0.592793,0.557769,AB01,NaN,NaN,False,Train,P1,AB01 P1 C022.JPG,P1
2,55,22,P4,P42,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,5,MildFattyLiver,...,0.653137,0.703187,AB01,NaN,NaN,False,Train,P5,AB01 P4-2 C022.JPG,P5
3,56,22,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,5,MildFattyLiver,...,0.698556,0.750996,AB01,NaN,NaN,False,Train,P3,AB01 P3-1 C022.JPG,P3
4,57,22,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,5,MildFattyLiver,...,0.655971,0.703187,AB01,NaN,NaN,False,Train,P4,AB01 P4-1 C022.JPG,P4

In [15]:
fold_df = df_merged[df_merged["fold"]!=5].reset_index(drop=True)
print("Fold: ", set(fold_df.fold))
print(fold_df.shape)
fold_df.head()

Fold:  {3, 4, 6, 7, 8, 9, 10}
(4598, 27)

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Rwidth,Rheight,Sub_class_New,tag_AjNit,tag_AjWan,Test150,Spilt,Sub_Position_New,filename,Sub_Position_Label
0,34,42,P5,P52,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,7,MildFattyLiver,...,0.633663,0.651394,AB01,NaN,NaN,False,Train,None,AB01 P5-2 C042.JPG,P7
1,35,42,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,7,ModerateFattyLiver,...,0.541516,0.422222,AB02,NaN,NaN,False,Train,P1,AB02 P1 C042.JPG,P1
2,36,42,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,7,ModerateFattyLiver,...,0.494585,0.610101,AB02,NaN,NaN,False,Train,P2,AB02 P2 C042.JPG,P2
3,37,42,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,7,ModerateFattyLiver,...,0.494545,0.668687,AB02,NaN,NaN,False,Train,P6,AB02 P5-1 C042.JPG,P6
4,38,42,P4,P42,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,7,ModerateFattyLiver,...,0.477148,0.690909,AB02,NaN,NaN,False,Train,P5,AB02 P4-2 C042.JPG,P5

In [11]:
df_merged.to_csv('/media/tohn/HDD/VISION_dataset/Traindf_fold3_10_Kfold.csv')

## DATASET: Test Set

In [6]:
datatest = pd.read_csv( '/media/tohn/HDD/VISION_dataset/Testdf_fold1_2_v1.csv')
print(set(datatest.fold))
print(datatest.shape)
datatest.head()

{1, 2}
(1312, 27)

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Rwidth,Rheight,Sub_class_New,tag_AjNit,tag_AjWan,Test150,Spilt,Sub_Position_New,filename,Sub_Position_Label
0,111,40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,0.513514,0.346614,AB01,NaN,NaN,False,Test,P1,AB01 P1 C040.JPG,P1
1,112,40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,0.560377,0.428287,AB01,NaN,NaN,False,Test,P2,AB01 P2 C040.JPG,P2
2,113,40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,0.667984,0.711155,AB01,NaN,NaN,False,Test,P4,AB01 P4-1 C040.JPG,P4
3,114,40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,0.690385,0.653386,AB01,NaN,NaN,False,Test,P6,AB01 P5-1 C040.JPG,P6
4,115,40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,0.672515,0.625498,AB01,NaN,NaN,False,Test,P3,AB01 P3-1 C040.JPG,P3